# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

schema_version = "1.1"

[task]
name = "local/078-add-wednesday-lecture"
description = "Could you please add a two-hour lecture slot to my weekly course timetable, scheduled for every Wednesday at 12 PM? It seems I accidentally omitted that when setting up my schedule"
authors = []
keywords = ["os", "calc", "osworld", "multi_apps", "078-add-wednesday-lecture"]

[metadata]
category = "os"
difficulty = "medium"

[verifier]
timeout_sec = 2400.0
user = "agent"

[agent]
timeout_sec = 2400.0
user = "agent"

[environment]
build_timeout_sec = 2400.0
cpus = 2
memory_mb = 4096
storage_mb = 20480
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]
[environment.env]
[solution.env]
