# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

schema_version = "1.1"

[task]
name = "local/027-add-dota-dlc-cart"
description = "Use Chrome to find Dota 2 on Steam and add all DLC to the cart."
authors = []
keywords = ["chrome", "osworld", "browser", "steam", "shopping-cart", "dota-2", "dlc"]

[metadata]
category = "browser"
difficulty = "medium"

[verifier]
timeout_sec = 2400.0
user = "agent"

[agent]
timeout_sec = 2400.0
user = "agent"

[environment]
build_timeout_sec = 2400.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]
[environment.env]
[solution.env]
