# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

schema_version = "1.1"

[task]
name = "local/074-apa-references-review"
description = "Could you please take a moment to review the 'case study' file located within the 'student work' folder? I'm particularly interested in ensuring that the references section at the end of the document adheres to the APA 7th edition formatting guidelines"
authors = []
keywords = ["osworld", "multi_apps", "074-apa-references-review"]

[metadata]
category = "multi-apps"
difficulty = "medium"

[verifier]
timeout_sec = 2400.0
user = "agent"

[agent]
timeout_sec = 2400.0
user = "agent"

[environment]
build_timeout_sec = 2400.0
cpus = 2
memory_mb = 4096
storage_mb = 20480
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]
[environment.env]
[solution.env]
