# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

schema_version = "1.1"

[task]
name = "local/109-setup-outlook-account"
description = "Use Thunderbird to fill the Outlook account setup page"
authors = []
keywords = ['thunderbird', 'email', 'osworld', 'a11y']

[metadata]
category = "email"
difficulty = "hard"

[verifier]
timeout_sec = 2400.0
user = "agent"

[agent]
timeout_sec = 2400.0
user = "agent"

[environment]
build_timeout_sec = 2400.0
cpus = 2
memory_mb = 4096
storage_mb = 12288
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]
[environment.env]
[solution.env]
