# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

schema_version = "1.1"

[task]
name = "local/063-red-slide-numbers"
description = "I am preparing a PPT in Libreoffice impress. The slide number is barely visible to me. Please help me change the color of the slide number to red?"
authors = []
keywords = ["libreoffice-impress", "slides", "osworld", "check_page_number_colors", "slide", "number", "color", "red"]

[metadata]
category = "presentation-editing"
difficulty = "medium"

[verifier]
timeout_sec = 2400.0
user = "agent"

[agent]
timeout_sec = 2400.0
user = "agent"

[environment]
build_timeout_sec = 2400.0
cpus = 1
memory_mb = 3072
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
