# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

schema_version = "1.1"

[task]
name = "local/021-fill-ramp-chart"
description = "I have computed the acceleration in row 2, and I want you to fill out the remaining rows for columns B and D. Next, concatenate the values from columns A to D, including their headers (the pattern is \"Header: cell value, ..., Header: cell value\"), into a new column named \"Combined Data\" for all rows. In the new column, keep only 2 decimal digits."
authors = []
keywords = ["libreoffice-calc", "spreadsheet", "osworld", "compare_table", "ramp", "up", "and", "down"]

[metadata]
category = "spreadsheet-editing"
difficulty = "medium"

[verifier]
timeout_sec = 2400.0
user = "agent"

[agent]
timeout_sec = 2400.0
user = "agent"

[environment]
build_timeout_sec = 2400.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[verifier.env]

[environment.env]

[solution.env]
